"""Investment theme catalog and derived keyword index.

Provides the THEMES list (theme_name_ko, theme_key, emoji, keywords) consumed by
ThemeSummarizer in summarizer.py, along with rendering-related constants and the
derived _THEME_NAME_KEYWORDS set used for cross-theme keyword filtering.

Extracted from summarizer.py to keep that module focused on the summarization
pipeline. No business logic lives here — only static data.
"""

from typing import List, Tuple

# Theme definitions: (theme_name_ko, theme_key, emoji, keywords)
THEMES: List[Tuple[str, str, str, List[str]]] = [
    (
        "규제/정책",
        "regulation",
        "🔵",
        [
            "sec",
            "cftc",
            "fca",
            "regulation",
            "regulatory",
            "compliance",
            "규제",
            "금융위",
            "금감원",
            "mica",
            "esma",
            "mas",
            "법안",
            "bill",
            "enforcement",
            "lawsuit",
            "소송",
            "제재",
            "금융감독원",
            "자본시장법",
            "mifid",
            "doj",
            "fbi",
            "irs",
            "audit",
            "감사",
            "처분",
            "stablecoin bill",
            "market structure",
            "cbdc",
        ],
    ),
    (
        "DeFi",
        "defi",
        "🟣",
        [
            "defi",
            "dex",
            "yield",
            "lending",
            "tvl",
            "liquidity",
            "aave",
            "uniswap",
            "compound",
            "staking",
            "restaking",
            "bridge",
            "swap",
            "pool",
            "vault",
            "amm",
            "lp",
            "impermanent",
            "curve",
            "maker",
            "ondo",
            "rwa",
            "tokenized",
            "real world asset",
            "intent",
            "chain abstraction",
            "payfi",
        ],
    ),
    (
        "비트코인",
        "bitcoin",
        "🟠",
        [
            "bitcoin",
            "btc",
            "mining",
            "halving",
            "비트코인",
            "채굴",
            "satoshi",
            "lightning network",
            "ordinals",
            "runes",
            "etf",
            "miner",
            "마이너",
            "hash rate",
            "해시레이트",
            "hodl",
            "whale",
            "고래",
            "accumulation",
            "block reward",
            "spot etf",
            "strategic reserve",
            "taproot",
        ],
    ),
    (
        "이더리움",
        "ethereum",
        "🔷",
        [
            "ethereum",
            "eth",
            "layer2",
            "rollup",
            "이더리움",
            "solidity",
            "evm",
            "l2",
            "blob",
            "dencun",
            "arbitrum",
            "optimism",
            "base",
            "zksync",
            "starknet",
            "polygon",
            "scroll",
            "mantle",
            "linea",
            "pectra",
            "eip",
            "gasless",
            "account abstraction",
            "verkle",
            "blob space",
        ],
    ),
    (
        "AI/기술",
        "ai_tech",
        "🤖",
        [
            "artificial intelligence",
            "gpu",
            "인공지능",
            "machine learning",
            "chatgpt",
            "nvidia",
            "반도체",
            "엔비디아",
            "openai",
            "anthropic",
            "semiconductor",
            "tsmc",
            "ai model",
            "생성형 ai",
            "apple",
            "meta",
            "google",
            "microsoft",
            "데이터센터",
            "cloud",
            "클라우드",
            "ai chip",
            "hbm",
            "딥시크",
            "deepseek",
            "llm",
            "transformer",
            "ai agent",
            "inference",
            "sovereign ai",
        ],
    ),
    (
        "매크로/금리",
        "macro",
        "📊",
        [
            "fed",
            "interest rate",
            "inflation",
            "금리",
            "한국은행",
            "gdp",
            "cpi",
            "fomc",
            "rate cut",
            "rate hike",
            "환율",
            "물가",
            "실업률",
            "고용",
            "소비자물가",
            "pce",
            "기준금리",
            "양적완화",
            "양적긴축",
            "treasury",
            "채권",
            "powell",
            "파월",
            "boj",
            "ecb",
            "경제성장",
            "gdp성장",
            "무역수지",
            "경상수지",
            "nonfarm",
            "비농업",
        ],
    ),
    (
        "거래소",
        "exchange",
        "🏦",
        [
            "binance",
            "coinbase",
            "exchange",
            "listing",
            "거래소",
            "upbit",
            "bithumb",
            "bybit",
            "okx",
            "kraken",
            "상장",
            "상장폐지",
            "delisting",
            "coinone",
            "korbit",
            "htx",
            "gate",
            "bitget",
            "거래량",
            "volume",
            "ipo",
            "자진상폐",
        ],
    ),
    (
        "보안/해킹",
        "security",
        "🔴",
        [
            "hack",
            "exploit",
            "vulnerability",
            "security",
            "해킹",
            "breach",
            "phishing",
            "scam",
            "rug pull",
            "drain",
            "flash loan",
            "oracle",
            "재진입",
            "bridge exploit",
            "front-running",
            "mev",
            "sandwich",
            "dusting",
            "smart contract bug",
            "취약점",
            "인증",
            "zero day",
            "social engineering",
            "private key",
        ],
    ),
    (
        "정치/정책",
        "politics",
        "🏛️",
        [
            "trump",
            "이재명",
            "election",
            "policy",
            "정책",
            "tariff",
            "sanction",
            "congress",
            "의회",
            "관세",
            "백악관",
            "대통령",
            "executive order",
            "행정명령",
            "biden",
            "바이든",
            "kamala",
            "의원",
            "senator",
            "representative",
            "입법",
            "legislation",
            "대선",
            "총선",
            "국회",
        ],
    ),
    (
        "NFT/Web3",
        "nft_web3",
        "🎨",
        [
            "nft",
            "metaverse",
            "web3",
            "opensea",
            "메타버스",
            "digital collectible",
            "gamefi",
            "socialfi",
            "creator",
        ],
    ),
    (
        "가격/시장",
        "price_market",
        "📈",
        [
            "price",
            "rally",
            "crash",
            "plunge",
            "시세",
            "상승",
            "하락",
            "급등",
            "급락",
            "폭락",
            "반등",
            "bull",
            "bear",
            "bullish",
            "bearish",
            "강세",
            "약세",
            "조정",
            "correction",
            "코스피",
            "코스닥",
            "나스닥",
            "다우존스",
            "금",
            "원유",
            "달러",
            "support",
            "resistance",
            "지지",
            "저항",
            "돌파",
            "breakout",
            "ath",
            "all-time high",
            "거래량",
            "volume",
            "매수",
            "매도",
            "시총",
            "market cap",
            "liquidation",
            "open interest",
            "funding rate",
        ],
    ),
]

TOP_THEMES_COUNT = 5
ARTICLES_PER_THEME = 5
# Overflow preview cap per theme — how many articles past the featured cards
# get a thumbnail preview in the <details> section. Raised from implicit 2 → 10
# so "그 외 38건 보기" expands into a visual list instead of a bare stub line.
OVERFLOW_PREVIEW_LIMIT = 10
BAR_WIDTH = 18

# Build a set of theme names (Korean + English keys) for cross-theme keyword filtering
_THEME_NAME_KEYWORDS: set = set()
for _t_name, _t_key, _t_emoji, _t_kws in THEMES:
    _THEME_NAME_KEYWORDS.add(_t_key.lower())
    _THEME_NAME_KEYWORDS.add(_t_name.lower())
    # Add Korean theme names without slash
    for _part in _t_name.split("/"):
        _THEME_NAME_KEYWORDS.add(_part.strip().lower())
